### ISSUE TITLE
relative paths

### ISSUE THREAD

**Issue by WDD-Marv** [slowikk/postcss-data-uri#4]
when used with gulp-postcss, relative paths don't work (see postcss-urlrev for something that behaves as expected).

i.e.:

```css
.reports-file-not-exists {
    background: data-uri('../img/thing.jpg') ;
}
.works {
    background: data-uri('./path/to/img/thing.jpg');
}
```
