### ISSUE TITLE
multiple backgrounds

### ISSUE THREAD

**Issue by WDD-Marv** [slowikk/postcss-data-uri#5]
it appears that one can't use multiple data-uris in the same background property:

```css
.foo {
    background: center, center, 0 0 ;
    background-repeat: no-repeat ;
    background-size: contain, contain, cover ;
    background-image: url('./foo.jpg'), data-uri('./foo.jpg'), data-uri('./foo.jpg') ;
}
```
